version: '3.9'

services:
  postgres-instance:
    image: postgres:13.6-bullseye
    restart: always
    container_name: postgres-instance
    hostname: postgres-instance
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: my_pass
      POSTGRES_USER: my_user
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
        - ./rabbitmq-data/:/var/lib/rabbitmq/


  auth-service:
    container_name: auth-service_container
    hostname: auth-service
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-instance:5432/local_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_pass
    depends_on:
      - postgres-instance    

  order:
    container_name: order_container
    hostname: order_service
    build: ./order
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-instance:5432/local_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_pass 
    depends_on:
      - postgres-instance   

  notification:
    container_name: notification_container
    hostname: notification_service
    build: ./notification
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-instance:5432/local_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_pass    
    depends_on:
      - postgres-instance

  product:
    container_name: product_container
    hostname: product_service
    build: ./product
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-instance:5432/local_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_pass     
    depends_on:
      - postgres-instance


  package_and_delivery:
    container_name: packageAnddelivery_container
    hostname: packageAnddelivery_service
    build: ./packageAnddelivery
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-instance:5432/local_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_pass   
    depends_on:
      - postgres-instance
                          
